
# services:
#   rabbitmq:
#     image: rabbitmq:3-management
#     ports:
#       - "5672:5672"   # AMQP protocol port
#       - "15672:15672" # Management UI port
#     volumes:
#       - rabbitmq_data:/var/lib/rabbitmq
#     healthcheck:
#       test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
#       interval: 30s
#       timeout: 10s
#       retries: 5

#   server:
#     build: 
#       context: ./server
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=production
#       - RABBITMQ_URL=amqp://rabbitmq:5672
#     volumes:
#       - uploads:/app/uploads
#     depends_on:
#       rabbitmq:
#         condition: service_healthy

#   processing-service:
#     build: 
#       context: ./processing-service
#     environment:
#       - RABBITMQ_URL=amqp://rabbitmq:5672
#       - UPLOADS_DIR=/app/uploads
#     volumes:
#       - uploads:/app/uploads
#     depends_on:
#       rabbitmq:
#         condition: service_healthy

# volumes:
#   rabbitmq_data:
#   uploads: 