version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:
      - ./server:/app
      - /app/node_modules
      - uploads:/app/uploads
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy

  processing-service:
    build: 
      context: ./processing-service
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - UPLOADS_DIR=/app/uploads
      - PYTHONUNBUFFERED=1
    volumes:
      - ./processing-service:/app
      - uploads:/app/uploads
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  rabbitmq_data:
  uploads: 